name: CodeCov
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
           
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.x'
#         architecture: 'x64'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
        
#     - name: Generate Report
#       run: |
#         pip install coverage
#         coverage run -m unittest
#     - name: Upload Coverage to Codecov
#       uses: codecov/codecov-action@v2
