name: hw2-staticanalysis
on: [push]

jobs:
  autopep8:
    name: Run autopep8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install autopep8
      - name: Run autopep8
        run: |
          autopep8 --in-place --aggressive --aggressive hw2/*.py

  pylint:
    name: Run pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pylint
      - name: Run pylint
        run: |
          pylint hw2/*.py

  pyright:
    name: Run pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pyright
      - name: Run pyright
        run: |
          pyright hw2/*.py